default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host:     <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

  # --- THIS IS THE SMART PART ---
  # It takes your app's name and adds the current environment to it.
  # e.g., "hash_media_development", "hash_media_production", etc.
  database: <%= ENV["DATABASE_NAME"] %>

  volumes:
    - postgres_data:/var/lib/postgresql/data

# Each environment below simply inherits all the settings from the default block.
development:
  <<: *default

test:
  <<: *default

production:
  # The primary, cable, queue, and cache will all inherit the settings
  # from the default block, including the dynamically generated database name.
  primary:
    <<: *default
  cable:
    <<: *default
  queue:
    <<: *default
  cache:
    <<: *default
